/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ReservarCitaRouteImport } from './routes/reservar-cita'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GestionarCitaRouteImport } from './routes/gestionar-cita'
import { Route as ConfirmacionCitaRouteImport } from './routes/confirmacion-cita'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutItemsRouteImport } from './routes/_layout/items'
import { Route as LayoutCitasPendientesRouteImport } from './routes/_layout/citas-pendientes'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservarCitaRoute = ReservarCitaRouteImport.update({
  id: '/reservar-cita',
  path: '/reservar-cita',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GestionarCitaRoute = GestionarCitaRouteImport.update({
  id: '/gestionar-cita',
  path: '/gestionar-cita',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmacionCitaRoute = ConfirmacionCitaRouteImport.update({
  id: '/confirmacion-cita',
  path: '/confirmacion-cita',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutItemsRoute = LayoutItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCitasPendientesRoute = LayoutCitasPendientesRouteImport.update({
  id: '/citas-pendientes',
  path: '/citas-pendientes',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/confirmacion-cita': typeof ConfirmacionCitaRoute
  '/gestionar-cita': typeof GestionarCitaRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reservar-cita': typeof ReservarCitaRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/citas-pendientes': typeof LayoutCitasPendientesRoute
  '/items': typeof LayoutItemsRoute
  '/settings': typeof LayoutSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/confirmacion-cita': typeof ConfirmacionCitaRoute
  '/gestionar-cita': typeof GestionarCitaRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reservar-cita': typeof ReservarCitaRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/citas-pendientes': typeof LayoutCitasPendientesRoute
  '/items': typeof LayoutItemsRoute
  '/settings': typeof LayoutSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/confirmacion-cita': typeof ConfirmacionCitaRoute
  '/gestionar-cita': typeof GestionarCitaRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reservar-cita': typeof ReservarCitaRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/citas-pendientes': typeof LayoutCitasPendientesRoute
  '/_layout/items': typeof LayoutItemsRoute
  '/_layout/settings': typeof LayoutSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/confirmacion-cita'
    | '/gestionar-cita'
    | '/login'
    | '/recover-password'
    | '/reservar-cita'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/citas-pendientes'
    | '/items'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/confirmacion-cita'
    | '/gestionar-cita'
    | '/login'
    | '/recover-password'
    | '/reservar-cita'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/citas-pendientes'
    | '/items'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/_layout'
    | '/confirmacion-cita'
    | '/gestionar-cita'
    | '/login'
    | '/recover-password'
    | '/reservar-cita'
    | '/reset-password'
    | '/signup'
    | '/_layout/admin'
    | '/_layout/citas-pendientes'
    | '/_layout/items'
    | '/_layout/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LayoutRoute: typeof LayoutRouteWithChildren
  ConfirmacionCitaRoute: typeof ConfirmacionCitaRoute
  GestionarCitaRoute: typeof GestionarCitaRoute
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ReservarCitaRoute: typeof ReservarCitaRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservar-cita': {
      id: '/reservar-cita'
      path: '/reservar-cita'
      fullPath: '/reservar-cita'
      preLoaderRoute: typeof ReservarCitaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gestionar-cita': {
      id: '/gestionar-cita'
      path: '/gestionar-cita'
      fullPath: '/gestionar-cita'
      preLoaderRoute: typeof GestionarCitaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirmacion-cita': {
      id: '/confirmacion-cita'
      path: '/confirmacion-cita'
      fullPath: '/confirmacion-cita'
      preLoaderRoute: typeof ConfirmacionCitaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/items': {
      id: '/_layout/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof LayoutItemsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/citas-pendientes': {
      id: '/_layout/citas-pendientes'
      path: '/citas-pendientes'
      fullPath: '/citas-pendientes'
      preLoaderRoute: typeof LayoutCitasPendientesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutCitasPendientesRoute: typeof LayoutCitasPendientesRoute
  LayoutItemsRoute: typeof LayoutItemsRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutCitasPendientesRoute: LayoutCitasPendientesRoute,
  LayoutItemsRoute: LayoutItemsRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LayoutRoute: LayoutRouteWithChildren,
  ConfirmacionCitaRoute: ConfirmacionCitaRoute,
  GestionarCitaRoute: GestionarCitaRoute,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ReservarCitaRoute: ReservarCitaRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
